# Generated by Django 5.2.12 on 2026-09-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdatasnapshot',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO code reported by the exchange, e.g. USD or INR.', max_length=8),
        ),
    ]
